export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST"
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE"

export const DELETE_STUDENTS_REQUEST = "DELETE_STUDENTS_REQUEST"
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS"
export const DELETE_STUDENTS_FAILURE = "DELETE_STUDENTS_FAILURE"

export const ADD_STUDENTS_REQUEST = "ADD_STUDENTS_REQUEST"
export const ADD_STUDENTS_SUCCESS = "ADD_STUDENTS_SUCCESS"
export const ADD_STUDENTS_FAILURE = "ADD_STUDENTS_FAILURE"


export const UPDATE_STUDENTS_REQUEST = "UPDATE_STUDENTS_REQUEST"
export const UPDATE_STUDENTS_SUCCESS = "UPDATE_STUDENTS_SUCCESS"
export const UPDATE_STUDENTS_FAILURE = "UPDATE_STUDENTS_FAILURE"